version: "3.9"

volumes:
  db:

services:
  web:
    build:
      target: web
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app/"
      - "./log:/app/log"
    env_file:
      - test.env
    ports:
      - "3000:3000"
    command: bash -c "rails s -b 0.0.0.0"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:14
    env_file:
      - test.env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_HOST=${DATABASE_HOST}
    volumes:
      - db:/var/lib/postgresql/data