default: &default
  clients:
    default:
      uri: <%= ENV.fetch("MONGO_URL") %>
      options:
        # The user's database roles.
        roles:
          - 'dbOwner'
        auth_source: admin

production:
  <<: *default

development:
  <<: *default

test:
  clients:
    default:
      uri: <%= ENV.fetch("MONGO_URL") %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
